#!/usr/bin/bash
set -eou pipefail

in_gfa=$1
out_prefix=$2
threads=8

out_dir=$(dirname "$out_prefix")

mkdir -p $out_dir

vg convert --gfa-in $in_gfa --packed-out --threads $threads > $out_prefix.vg
vg index $out_prefix.vg --threads $threads --dist-name $out_prefix.dist --progress