# ANCHOR PARAMETERS CONSTANTS
MAX_PATHS_IN_SNARLS = 1000
MIN_ANCHOR_LENGTH = 16
MIN_NODES_IN_ANCHOR = 2

#ANCHOR DICTIONARY CONSTRUCTION CONSTANTS
FORWARD_DICTIONARY = 0
REVERSE_DICTIONARY = 1
PEEK_SIZE = 100000000
END_NODE_POS = 0
SNARL_ID_POS = 1

#SHASTA CONSTANTS
MIN_SHASTA_REVIO = 0
MIN_SHASTA_R10 = 0

# PLOT CONSTANTS
RANGES = [1,5,10,20,40,60,100,1000]
NUM_BINS = 40

# GAF PARSING CONSTANTS
EXPECTED_GAF_TAGS = 16
EXPECTED_MAP_Q = 1
MIN_CS_LEN = 6

READ_NAME_ID = 0
READ_LEN = 1
RELATIVE_STRAND_ID = 4
PATH_ID = 5
PATH_START_ID = 7
PATH_END_ID = 8
MAP_Q_ID = 11
CS_TAG_ID = 14

# ALIGNMENT LIST CONSTANTS
READ_POSITION = 0
R_LEN_POSITION = 1
STRAND_POSITION = 2
START_POSITION = 3
END_POSITION = 4
NODE_POSITION = 5
ORIENTATION_POSITION = 6
CIGAR_POSITION = 7

# BP MATCHED READ LIST CONSTANTS
READ_ID = 0
READ_STRAND = 1
ANCHOR_START = 2
ANCHOR_END = 3
MATCH_LIMIT = 4
CS_LEFT_AVAIL = 5   # number of basepairs available for left extension in the current anchor
# this value is in the direction of read strand. # For forward strand reads, this is the number of basepairs available to the left of the anchor start node.
# For reverse strand reads, this will be in nodes with higher id than the highest node id in the anchor. 
CS_RIGHT_AVAIL = 6

# NODE/ANCHOR MERGING CONSTANTS
MIN_ANCHOR_READS = 2
HET_FRACTION_READS_RETAINED_THRESHOLD_FOR_MERGING = 0.9
HOMO_FRACTION_READS_RETAINED_THRESHOLD_FOR_MERGING = 0.4
MIN_READS_REQUIRED_FOR_MERGING_R0 = 9
MIN_READS_REQUIRED_FOR_MERGING_R1 = 3
MIN_ANCHOR_READCOV = 9 # an anchor readcov if dropped below this threshold, it should not be further extended
MIN_ANCHOR_READCOV_FOR_INDEPENDENT_ANCHOR_EXTENSION = 3
FRACTION_READS_FOR_SNARL_BOUNDARY_EXTENTION = 0.9
MIN_READS_REQUIRED_FOR_BOUNDARY_EXTENSION = 0
DROP_FRACTION = 0.1

# MAX_READ_DROPS_ALLOWED = 3      # max drops allowed while extension if readcov of an anchor is greater than MIN_ANCHOR_READCOV + MAX_READ_DROPS_ALLOWED

# PHASING CONSISTENCY CHECK ANCHORS/SNARLS CONSTANTS
MIN_SNARL_LINKAGE_THRESHOLD = 3
RELIABLE_SNARL_FRACTION_THRESHOLD = 0.1
