# ANCHOR PARAMETERS CONSTANTS
MAX_PATHS_IN_SNARLS = 90
MIN_ANCHOR_LENGTH = 100
MIN_NODES_IN_ANCHOR = 2

# GAF PARSING CONSTANTS
EXPECTED_GAF_TAGS = 16
EXPECTED_MAP_Q = 60
MIN_CS_LEN = 6

READ_NAME_ID = 0
READ_LEN = 1
RELATIVE_STRAND_ID = 4
PATH_ID = 5
PATH_START_ID = 7
PATH_END_ID = 8
MAP_Q_ID = 11
CS_TAG_ID = 14

# ALIGNMENT LIST CONSTANTS
READ_P = 0
R_LEN_P = 1
STRAND_P = 2
START_P = 3
END_P = 4
NODE_P = 5
ORIENT_P = 6
CS_P = 7

READS_DEPTH = 1
