# ANCHOR PARAMETERS CONSTANTS
MAX_PATHS_IN_SNARLS = 90
MIN_ANCHOR_LENGTH = 100
MIN_NODES_IN_ANCHOR = 2

#ANCHOR DICTIONARY CONSTRUCTION CONSTANTS
FORWARD_DICTIONARY = 0
REVERSE_DICTIONARY = 1
PEEK_SIZE = 5
END_NODE_POS = 0
SNARL_ID_POS = 1

#SHASTA CONSTANTS
MIN_SHASTA_REVIO = 0
MIN_SHASTA_R10 = 0

# PLOT CONSTANTS
RANGES = [1,5,10,20,40,60,100,1000]
NUM_BINS = 40

# GAF PARSING CONSTANTS
EXPECTED_GAF_TAGS = 16
EXPECTED_MAP_Q = 0
MIN_CS_LEN = 6

READ_NAME_ID = 0
READ_LEN = 1
RELATIVE_STRAND_ID = 4
PATH_ID = 5
PATH_START_ID = 7
PATH_END_ID = 8
MAP_Q_ID = 11
CS_TAG_ID = 14

# ALIGNMENT LIST CONSTANTS
READ_POSITION = 0
R_LEN_POSITION = 1
STRAND_POSITION = 2
START_POSITION = 3
END_POSITION = 4
NODE_POSITION = 5
ORIENTATION_POSITION = 6
CIGAR_POSITION = 7

READS_DEPTH_HETEROZYGOUS = 5
SNARL_DEPTH_HETEROZYGOUS = 20
READS_DEPTH_HOMOZYGOUS = 20
